### ISSUE TITLE
1.2.0 Server Crash

### ISSUE THREAD

**Issue by sumrex** [Peatral/EmbersConstruct#1]
Crashes on my server. You are calling a ClientProxy on the server according to this log.

[crash-2020-03-30_02.04.35-server.txt](https://github.com/Peatral/EmbersConstruct/files/4401076/crash-2020-03-30_02.04.35-server.txt)

**Comment by Peatral** [comment]
Ahhh, dammit, I did not test it on a server but the mistake I did is pretty obvious, I autoregister the clientproxy and gets called serverside. So I just have to move the event and not autoregister the ClientProxy. I don't know what rode my mind when I wrote this.
[(EXTRACT THIS)](https://github.com/Peatral/EmbersConstruct/files/4401592/embersconstruct-1.12.2-1.2.1-SNAPSHOT.zip)
I dont want to make a release for every little change, this version should fix the crash (This time I tested it on a local server ;D)
