### ISSUE TITLE
[Suggestion] Config options to disable the Kiln, Stamp Table, and Bloomery

### ISSUE THREAD

**Issue by drhaber** [Peatral/EmbersConstruct#14]
It would be really awesome if there was a config option to disable the Kiln, Stamp Table, and bloomery

This would be a tremendous help as currently those three items do not fit well into the progression system of my pack.

**Comment by Peatral** [comment]
If you disable the stamp table and the kiln there would be no way to obtain the stamps (generally speaking of course, I don't know how your progression works instead). For the bloomery I actually planned on making it optional. Although disabling the stamp table and kiln seems illogical to me I may look into it.

**Comment by Peatral** [comment]
I implemented it in the new release. You can now disable/enable the kiln, bloomery and stamp table. This doesn't remove the blocks itself but the recipes to craft them, the recipes you use them for and they get removed from the creative tab.
(So they are still visible in JEI but don't have a use)
