### ISSUE TITLE
Update chinese language file

### ISSUE THREAD

**Issue by Peatral** [Peatral/EmbersConstruct#16]
@TUsama it would be nice if you could update the chinese language file, it is currently missing quite some stuff.

**Comment by TUsama** [comment]
ok, It's my pleasure. But it's 12 p.m. now in china, I'll work into in several hours later. ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Christof&amp;nbsp;Reimers&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月13日(星期六) 晚上11:34
收件人:&nbsp;&quot;Peatral/EmbersConstruct&quot;<EmbersConstruct@noreply.github.com&gt;;
抄送:&nbsp;&quot;Clefal&quot;<1716976420@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;[Peatral/EmbersConstruct] Update chinese language file (#16)

**Comment by Peatral** [comment]
Thats fine, just wanted to let you know ^^
