### ISSUE TITLE
support for tweakers construct

### ISSUE THREAD

**Issue by Blaise1502** [Peatral/EmbersConstruct#20]
When I use tweakers construct to modify how much it costs to make a part it does not translate to the stamps to make the parts. so if i make the pick head cost 3 in tweakers construct it will not convey over to the stamp and the end result means you can dupe your materials infinitely. reverse for values less than default, means you will lose materials infinitely if you recycle old or incorrect parts

**Comment by Peatral** [comment]
This is probably because the recipes get copied before they get modified, I will take a look.

**Comment by Peatral** [comment]
Should be fixed with 5546be984e24ea57f4060d00479d07b3ca7feaed. Will probably release a fix soon.
